kind: ConfigMap 
apiVersion: v1 
metadata:
  name: eaycliam-backend-configmap 
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://35.226.149.202:3306/test
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
