apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyclaim-backend
  namespace: easyclaim
  labels:
    name: easyclaim-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: easyclaim-backend
  strategy:
    type: Recreate
  template:
    metadata:
      name: easyclaim-backend
      labels:
        name: easyclaim-backend
    spec:
      containers:
        - name:  easyclaim-backend
          image: vigneshsweekaran/easyclaim-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: "/config"
      volumes:
      - name: config-volume
        configMap:
          name: eaycliam-backend-configmap
          items:
          - key: application.properties
            path: application.properties

---
apiVersion: v1
kind: Service
metadata:
  name: easyclaim-backend
  namespace: easyclaim
  labels:
    name: easyclaim-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: easyclaim-backend
  type: ClusterIP
