kind: ConfigMap 
apiVersion: v1 
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
data:
  application: |-
    spring.datasource.url=jdbc:mysql://mysql:3306/test
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
